version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: job-recommender-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: job-recommender-backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - JOOBLE_API_KEY=${JOOBLE_API_KEY}
      - CAREERJET_API_KEY=${CAREERJET_API_KEY}
    depends_on:
      - mongodb
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: job-recommender-frontend
    ports:
      - "8501:8501"
    environment:
      - API_HOST=http://backend
      - API_PORT=8000
    depends_on:
      - backend
    restart: always

volumes:
  mongo-data:
